/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7a02add8-78a8-44eb-9492-b9ce02a8538f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rqF8PRoYa",
    "aws_user_pools_web_client_id": "79aofaj583i09sres0e2pkbp33",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6w6bbwod7bb7veu3n6x6al37au.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
